api:
  build: .
  volumes:
    - ../backend:/apps/ems-api
  working_dir: /apps/ems-api
  ports:
    - 81:80
  links:
    - mysql
  environment:
    MYSQL_DATABASE: ems
    MYSQL_USER: ems
    MYSQL_PASSWORD: ems@123456

mysql:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: ems
    MYSQL_USER: ems
    MYSQL_PASSWORD: ems@123456
  volumes:
    - ./mysqldata:/var/lib/mysql
  ports:
    - 33061:3306

redis:
  image: redis:latest
  ports:
    - 6379:6379